AguasSetubal/Controllers/API/InvoicesController.cs
using AguasSetubal.Data;
using AguasSetubal.Helpers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AguasSetubal.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class InvoicesController : Controller
    {
        private readonly IInvoicesRepository _invoicesRepository;
        private readonly IMailHelper _mailHelper;

        public InvoicesController(IInvoicesRepository invoicesRepository, IMailHelper mailHelper)
        {
            _invoicesRepository = invoicesRepository;
            _mailHelper = mailHelper;
        }

        [HttpGet("SendLastInvoice")]
        public IActionResult SendLastInvoice()
        {
            var fatura = _invoicesRepository.GetLastInvoice();
            if (fatura == null)
            {
                return NotFound("Nenhuma fatura em aberto encontrada para este cliente.");
            }

            // Montar a mensagem da fatura
            string mensagem = $@"
            <html>
                <body style='font-family: Arial, sans-serif;'>
                    <h2 style='color: #4CAF50;'>Detalhes da Fatura</h2>
                    <p><strong>Fatura ID:</strong> {fatura.Id}</p>
                    <p><strong>Data de Emissão:</strong> {fatura.DataEmissao:dd/MM/yyyy}</p>
                    <p><strong>Valor Total:</strong> <span style='color: #FF5733;'>{fatura.ValorTotal:C}</span></p>
                    <p style='font-size: 12px; color: #FF4500;'>Dirija-se a sua area de cliente para obter dados para pagamento do valor.</p>
                    <hr style='border: 1px solid #ccc;'/>                    
                    <p style='font-size: 12px; color: #888;'>Esta é uma mensagem automática, por favor, não responda.</p>
                </body>
            </html>";

            // Enviar o e-mail
            _mailHelper.SendEmail(fatura.Cliente.Email, "A sua última fatura a pagamento", mensagem);

            return Ok("Fatura enviada com sucesso.");
        }
    }
}

AguasSetubal/Controllers/LeituraContadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AguasSetubal.Data;
using AguasSetubal.Models;
using AguasSetubal.Helpers;
using AguasSetubal.Models.ViewModels;

namespace AguasSetubal.Controllers
{
    public class LeituraContadorController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IUserHelper _userHelper;

        public LeituraContadorController(ApplicationDbContext context, IUserHelper userHelper)
        {
            _context = context;
            _userHelper = userHelper;
        }

        // GET: LeituraContadors
        public async Task<IActionResult> Index(string id)
        {
            var listaLeituras = _context.LeituraContadores
                .Include(l => l.Contador)
                .Include(l => l.Cliente);

            if (id != null && listaLeituras != null && listaLeituras.Any())
            {
                var userId = await _userHelper.GetUserByNameAsync(id);

                var clientId = _context.Clientes.FirstOrDefault(c => c.UserId == userId.Id)?.Id;

                var listaLeiturasPorCliente = _context.LeituraContadores
                .Include(f => f.Cliente)
                .Include(f => f.Contador)
                .Where(c => c.ClienteId == clientId);

                return View(await listaLeiturasPorCliente.ToListAsync());
            }

            return View(await listaLeituras.ToListAsync());
        }

        // GET: LeituraContadors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leituraContador = await _context.LeituraContadores
                .Include(l => l.Contador)
                .Include(l => l.Cliente)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (leituraContador == null)
            {
                return NotFound();
            }

            return View(leituraContador);
        }

        // GET: LeituraContadors/Create
        public async Task<IActionResult> CreateAsync(string id)
        {
            LeituraContadorViewModel novaLeitura = new LeituraContadorViewModel();
            novaLeitura.DataLeitura = DateTime.Now;

            var clientes = _context.Clientes;
            ViewBag.Clientes = new SelectList(clientes, "Id", "Nome");

            if (id != null)
            {
                var user = await _userHelper.GetUserByNameAsync(id);

                var clientesPorId = _context.Clientes
                  .Where(c => c.UserId == user.Id && c.UserId != null).ToList();

                ViewBag.Clientes = new SelectList(clientesPorId, "Id", "Nome");
                novaLeitura.UserId = id;
            }

            return View(novaLeitura);
        }

        // POST: LeituraContadors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(LeituraContadorViewModel leituraContadorVM)
        {
            if (ModelState.IsValid)
            {
                var leituraContador = new LeituraContador
                {
                    LeituraAnterior = leituraContadorVM.LeituraAnterior,
                    LeituraAtual = leituraContadorVM.LeituraAtual,
                    Consumo = leituraContadorVM.Consumo,
                    DataLeitura = leituraContadorVM.DataLeitura,
                    IsInvoiced = leituraContadorVM.IsInvoiced,
                    ClienteId = leituraContadorVM.ClienteId,
                    FaturaId = leituraContadorVM.FaturaId,
                    ContadorId = leituraContadorVM.ContadorId
                };

                _context.Add(leituraContador);
                await _context.SaveChangesAsync();

                if (leituraContadorVM.UserId == string.Empty)
                    return RedirectToAction(nameof(Index));
                else
                    return RedirectToAction(nameof(Index), new { id = leituraContadorVM.UserId });
            }

            ViewData["ContadorId"] = new SelectList(_context.Contador, "Id", "Id", leituraContadorVM.ContadorId);
            ViewData["FaturaId"] = new SelectList(_context.Faturas, "Id", "Id", leituraContadorVM.FaturaId);

            return View(leituraContadorVM);
        }

        // GET: LeituraContadors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leituraContador = await _context.LeituraContadores.FindAsync(id);
            if (leituraContador == null)
            {
                return NotFound();
            }
            ViewData["ContadorId"] = new SelectList(_context.Contador, "Id", "Id", leituraContador.ContadorId);
            ViewData["FaturaId"] = new SelectList(_context.Faturas, "Id", "Id", leituraContador.FaturaId);
            return View(leituraContador);
        }

        // POST: LeituraContadors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, LeituraContador leituraContador)
        {
            if (id != leituraContador.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(leituraContador);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LeituraContadorExists(leituraContador.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ContadorId"] = new SelectList(_context.Contador, "Id", "Id", leituraContador.ContadorId);
            ViewData["FaturaId"] = new SelectList(_context.Faturas, "Id", "Id", leituraContador.FaturaId);
            return View(leituraContador);
        }

        // GET: LeituraContadors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var leituraContador = await _context.LeituraContadores
                .Include(l => l.Contador)
                .Include(l => l.Fatura)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (leituraContador == null)
            {
                return NotFound();
            }

            return View(leituraContador);
        }

        // POST: LeituraContadors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var leituraContador = await _context.LeituraContadores.FindAsync(id);
            _context.LeituraContadores.Remove(leituraContador);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LeituraContadorExists(int id)
        {
            return _context.LeituraContadores.Any(e => e.Id == id);
        }

        [HttpPost]
        [Route("LeituraContador/GetCountersByClientId")]
        public JsonResult GetCountersByClientId(int clientId)
        {
            var contadoresCliente = _context.Contador
                .Include(l => l.Cliente)
                .Where(m => m.ClienteId == clientId);

            var list = contadoresCliente.Select(c => new SelectListItem
            {
                Text = c.NumeroContador + " / " + c.NumeroContrato,
                Value = c.Id.ToString()
            }).OrderBy(l => l.Value).ToList();

            list.Insert(0, new SelectListItem
            {
                Text = "(Selecione contador ...)",
                Value = ""
            });

            return Json(list);
        }

        [HttpPost]
        public JsonResult GetLastReadingByContadorId(int? contadorId)
        {

            var ultimaleitura = _context.LeituraContadores
                .OrderBy(i => i.Id)
                .LastOrDefault(m => m.ContadorId == contadorId);

            var lastReading = ultimaleitura != null ? ultimaleitura.LeituraAtual : 0;

            return Json(new { lastReading = lastReading });
        }

    }
}

AguasSetubal/Views/Invoices/Create.cshtml
@model AguasSetubal.Models.Fatura

<div class="container-fluid mt-4">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card shadow-lg mt-3">
                <div class="card-body">
                    <h4>Criar nova fatura</h4>
                    <hr />
                    <div class="row" id="createFaturaDiv">
                        <div class="col-md-8">
                            <form asp-action="Create">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="form-group">
                                    <label asp-for="ClienteId" class="control-label">Selecione o cliente</label>
                                    <select asp-for="ClienteId" class="form-control" asp-items="ViewBag.Clientes"></select>
                                    <span asp-validation-for="ClienteId" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="ContadorId" class="control-label">Selecione o contador</label>
                                    <select asp-for="ContadorId" class="form-control" asp-items="ViewBag.Contadores"></select>
                                    <span asp-validation-for="ContadorId" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DataInicio" class="control-label"></label>
                                    <input asp-for="DataInicio" class="form-control" />
                                    <span asp-validation-for="DataInicio" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DataFim" class="control-label"></label>
                                    <input asp-for="DataFim" class="form-control" />
                                    <span asp-validation-for="DataFim" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Create" class="btn btn-primary" />
                                    <a asp-action="Index">Back to List</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {

        $('#createFaturaDiv #ClienteId').on('change', function (e) {
            GetCountersByClientId($(this).val());
        });

        GetCountersByClientId($('#createFaturaDiv #ClienteId').val());


        function GetCountersByClientId(clientId) {

            $("#ContadorId").empty();
            $.ajax({
                url: '@Url.Action("GetCountersByClientId", "LeituraContador")',
                method: 'POST',
                data: { clientId: clientId },
                success: function (response) {

                    $.each(response, function (i, counter) {
                        $("#ContadorId").append('<option value="'
                            + counter.value + '">'
                            + counter.text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve counters.' + ex);
                }
            });
        }

    });

</script>

AguasSetubal/Views/Invoices/Delete.cshtml
@model AguasSetubal.Models.Fatura

@{
    ViewData["Title"] = "Eliminar Fatura";
}
<div class="container-fluid mt-4">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card shadow-lg mt-3">
                <div class="card-body">
                    <h4 class="text-primary">Tem a certeza que pretende eliminar a Fatura</h4>
                    <hr />
                    <dl class="row">
                        <!-- Nome do Cliente -->
                        <dt class="col-sm-2">
                            Nome do Cliente
                        </dt>
                        <dd class="col-sm-10">
                            @Model.Cliente.Nome
                        </dd>

                        <!-- Valor Total -->
                        <dt class="col-sm-2">
                            Valor Total
                        </dt>
                        <dd class="col-sm-10">
                            @Model.ValorTotal.ToString("F2") &euro;
                        </dd>

                        <!-- Outros campos da fatura -->
                        <!-- Adicione aqui outros campos se necessário -->
                    </dl>

                    <form asp-action="Delete">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Eliminar" class="btn btn-danger" />
                    </form>

                    <div class="mt-3">
                        <a asp-action="Index" class="btn btn-secondary">Voltar para Lista de Faturas</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

AguasSetubal/Views/Invoices/Details.cshtml
@model AguasSetubal.Models.Fatura

<div class="container-fluid mt-4">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card shadow-lg mt-3">
                <div class="card-body">
                    <h4>Detalhes da fatura</h4>
                    <hr />
                    <div class="invoice">
                        <h1 class="text-center company-name">Águas de Setúbal</h1>
                        <h2 class="text-center invoice-title">Fatura para Pagamento</h2>

                        <div class="invoice-details">
                            <p><strong>Nome do Cliente:</strong> @Model.Cliente.Nome</p>
                            <p><strong>Nº contrato:</strong> @Model.Contador.NumeroContrato</p>
                            <p><strong>Nº contador:</strong> @Model.Contador.NumeroContador</p>
                            <p><strong>Endereço:</strong> @Model.Contador.MoradaLocal</p>
                            <p><strong>Data de Emissão:</strong> @Model.DataEmissao.ToString("dd/MM/yyyy")</p>
                            <br />
                            <br />
                            <hr />
                            <p><strong>Escalão:</strong> @Model.Descritivo</p>
                            <p><strong>Consumo:</strong> @Model.ConsumoTotal</p>
                            <p><strong>Valor unitário:</strong> @Model.ValorUnitario</p>
                            <p><strong>Valor Total:</strong> @Model.ValorTotal</p>
                            <hr />
                            <br />
                            <br />
                            @* Adicionando as linhas de Entidade e Referência *@
                            <p><strong>Entidade:</strong> 100 200 300</p>
                            <p><strong>Referência:</strong> 25 36 @Model.Id</p>
                            <p><strong>Valor Total a Pagar (€):</strong> @Model.ValorTotal.ToString("F2")</p>
                            <p><strong>Referência Interna:</strong> STB-@Model.Id</p>
                        </div>
                    </div>

                    <div class="mt-4">
                        <a href="@Url.Action("ImprimirFatura", new { id = Model.Id })" target="_blank" class="btn btn-success btn-lg">
                            Imprimir
                        </a>
                        @if (this.User.IsInRole("Funcionario"))
                        {
                            <a asp-action="Index">Back to List</a>
                        }
                        else
                        {
                            <a asp-action="Index" asp-route-id="@this.User.Identity.Name">Back to List</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #e6f2ff; /* Tom suave de azul */
    }

    .invoice {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ddd;
        border-radius: 10px;
        background-color: #f9f9f9;
    }

    .company-name {
        color: #004080; /* Azul marinho */
        font-size: 2.5rem; /* Tamanho maior que o título da fatura */
        margin-bottom: 0; /* Remove espaço embaixo */
    }

    .invoice-title {
        color: #2E8B57; /* Verde marinho */
        font-size: 2rem; /* Tamanho ligeiramente menor que o nome da empresa */
        margin-top: 0; /* Remove espaço acima */
    }

    .invoice-details {
        margin-top: 20px;
    }

        .invoice-details p {
            font-size: 1.1rem;
            margin-bottom: 10px;
        }

    .text-center {
        text-align: center;
    }
</style>

AguasSetubal/Views/Invoices/Edit.cshtml
@model AguasSetubal.Models.Fatura

<div class="container-fluid mt-4">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card shadow-lg mt-3">
                <div class="card-body">
                    <h4>Editar fatura</h4>
                    <hr />
                    <div class="row" id="createFaturaDiv">
                        <div class="col-md-8">
                            <form asp-action="Edit" enctype="multipart/form-data">
                                <input type="hidden" asp-for="Id" />
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="form-group">
                                    <label asp-for="ClienteId" class="control-label">Selecione o cliente</label>
                                    <select asp-for="ClienteId" class="form-control" asp-items="ViewBag.Clientes"></select>
                                    <span asp-validation-for="ClienteId" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="ContadorId" class="control-label">Selecione o contador</label>
                                    <select asp-for="ContadorId" class="form-control" asp-items="ViewBag.Contadores"></select>
                                    <span asp-validation-for="ContadorId" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DataInicio" class="control-label"></label>
                                    <input asp-for="DataInicio" class="form-control" />
                                    <span asp-validation-for="DataInicio" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DataFim" class="control-label"></label>
                                    <input asp-for="DataFim" class="form-control" />
                                    <span asp-validation-for="DataFim" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Gravar" class="btn btn-primary" />
                                    <a asp-action="Index">Back to List</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {

        $('#createFaturaDiv #ClienteId').on('change', function (e) {
            GetCountersByClientId($(this).val());
        });

        GetCountersByClientId($('#createFaturaDiv #ClienteId').val());


        function GetCountersByClientId(clientId) {

            $("#ContadorId").empty();
            $.ajax({
                url: '@Url.Action("GetCountersByClientId", "LeituraContador")',
                method: 'POST',
                data: { clientId: clientId },
                success: function (response) {

                    $.each(response, function (i, counter) {
                        $("#ContadorId").append('<option value="'
                            + counter.value + '">'
                            + counter.text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve counters.' + ex);
                }
            });
        }

    });

</script>

AguasSetubal/Views/Invoices/ImprimirFatura.cshtml
@model AguasSetubal.Models.Fatura

@{
    Layout = null; // Remove o layout para impressão
}

<div class="invoice">
    <h1 class="text-center company-name">Águas de Setúbal</h1>
    <h2 class="text-center invoice-title">Fatura para Pagamento</h2>

    <div class="invoice-details">
        <p><strong>Nome do Cliente:</strong> @Model.Cliente.Nome</p>
        <p><strong>Nº contrato:</strong> @Model.Contador.NumeroContrato</p>
        <p><strong>Nº contador:</strong> @Model.Contador.NumeroContador</p>
        <p><strong>Endereço:</strong> @Model.Contador.MoradaLocal</p>
        <p><strong>Data de Emissão:</strong> @Model.DataEmissao.ToString("dd/MM/yyyy")</p>
        <br />
        <br />
        <hr />
        <p><strong>Escalão:</strong> @Model.Descritivo</p>
        <p><strong>Consumo:</strong> @Model.ConsumoTotal</p>
        <p><strong>Valor unitário:</strong> @Model.ValorUnitario</p>
        <p><strong>Valor Total:</strong> @Model.ValorTotal</p>
        <hr />
        <br />
        <br />
        @* Adicionando as linhas de Entidade e Referência *@
        <p><strong>Entidade:</strong> 100 200 300</p>
        <p><strong>Referência:</strong> 25 36 @Model.Id</p>
        <p><strong>Valor Total a Pagar (€):</strong> @Model.ValorTotal.ToString("F2")</p>
        <p><strong>Referência Interna:</strong> STB-@Model.Id</p>
    </div>

    <div class="text-center mt-5">
        <button onclick="window.print();" class="btn btn-primary btn-lg">Imprimir Fatura</button>
    </div>
</div>

<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #e6f2ff; /* Tom suave de azul */
    }

    .invoice {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ddd;
        border-radius: 10px;
        background-color: #f9f9f9;
    }

    .company-name {
        color: #004080; /* Azul marinho */
        font-size: 2.5rem; /* Tamanho maior que o título da fatura */
        margin-bottom: 0; /* Remove espaço embaixo */
    }

    .invoice-title {
        color: #2E8B57; /* Verde marinho */
        font-size: 2rem; /* Tamanho ligeiramente menor que o nome da empresa */
        margin-top: 0; /* Remove espaço acima */
    }

    .invoice-details {
        margin-top: 20px;
    }

        .invoice-details p {
            font-size: 1.1rem;
            margin-bottom: 10px;
        }

    .text-center {
        text-align: center;
    }
</style>

AguasSetubal/Views/Invoices/Index.cshtml
@model IEnumerable<AguasSetubal.Models.Fatura>

@{
    ViewData["Title"] = "Faturas";
}

<div class="row">
    <div class="col-12 d-flex justify-content-between align-items-center">
        <h4 class="">@ViewData["Title"]</h4>
        @if (this.User.IsInRole("Funcionario"))
        {
            <a asp-action="Create" class="btn btn-primary">Criar nova Fatura</a>
        }
    </div>
    <div class="col-12">
        <div class="card shadow-lg mt-3">
            <div class="card-body p-0">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.First().Cliente.Nome)</th>
                                <th>@Html.DisplayNameFor(model => model.First().DataEmissao)</th>
                                <th>Consumo</th>
                                <th>Valor</th>
                                <th class="text-center">Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.Cliente.Nome)</td>
                                    <td>@Html.DisplayFor(modelItem => item.DataEmissao)</td>
                                    <td>@Html.DisplayFor(modelItem => item.ConsumoTotal)</td>
                                    <td>@Html.DisplayFor(modelItem => item.ValorTotal)</td>
                                    <td class="text-center">
                                        @if (this.User.IsInRole("Funcionario"))
                                        {
                                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning btn-sm mx-1"><i class="fas fa-edit"></i></a>
                                        }
                                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info btn-sm mx-1"><i class="fas fa-search"></i></a>
                                        @if (this.User.IsInRole("Funcionario"))
                                        {
                                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm mx-1"><i class="fas fa-trash"></i></a>
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>